### ISSUE TITLE
Request: Ability to Edit Templates More Easily

### ISSUE THREAD

**Issue by KharonAlpua** [mvdicarlo/postybirb#10]
Currently, templates can only be made from a post and include all of the post information, like tags and other settings. Templates have the potential to be a great tool, especially if you can use multiple templates per post, but only being able to make and save templates from the post interface itself makes it easy to build a template that is cluttered with information that is **not** template oriented.

Having a Templates tab so we can browse, edit, and create templates without having to prepare for an image upload would be a very nice feature.

**Comment by tecknojock** [comment]
I very much agree. Being able to layer templates would be fantastic.

**Comment by mvdicarlo** [comment]
This is something that is being supported in the remake.

**Comment by mvdicarlo** [comment]
Done in v2.x
