### ISSUE TITLE
ToS compliance concern

### ISSUE THREAD

**Issue by tanshoku** [mvdicarlo/postybirb#103]
What is the risk of losing one's account from using postybirb? I know that discord, for example, doesn't like people fiddling around with their API and can ban you for using third-party clients, as it happened to the creator of [cordless](https://github.com/Bios-Marcel/cordless). I've also heard rumours of people being banned from twitter for using third-party post scheduling tools, but I don't have any source for that. So, what's the actual risk of using this tool (if it's even possible to gauge that)?

**Comment by tecknojock** [comment]
While I cant speak to twitter, the discord posts use discord webhooks which are explicitly for this purpose. Its not the same as using their user API, and is completely within the realm of discord's ToS

**Comment by tanshoku** [comment]
I see. What about FurAffinity, DeviantArt and tumblr? I knew someone who was trying to develop an android app for FurAffinity a few years ago and got multiple test accounts banned, but I suspect they might have spammed the API somehow.

**Comment by tecknojock** [comment]
Re: FA
https://twitter.com/Dragoneer/status/1365022723186032646

This is an explicit endorsement from the current owner of FA ;)

**Comment by mvdicarlo** [comment]
I have not received any reports of banned accounts as a result of using the app yet.
So to my best knowledge, none.
