### ISSUE TITLE
[Request/Question] possible inkblot.art, buzzly.art, and ArtFight support?

### ISSUE THREAD

**Issue by ddigii** [mvdicarlo/postybirb#104]
Title - Buzzly and Inkblot are new sites and their features are currently being user tested, so it's easy to contact the devs if needed. ArtFight has been around for a while, but since it's volunteer-run they're also fairly simple to get ahold of. I'm not sure what their APIs are like, but the utility would be much appreciated in the future if possible :]

**Comment by GlitchyPSIX** [comment]
Would like to tap on this saying that Artfight has no public facing API, so it's unlikely

**Comment by Deer-Spangle** [comment]
Most of the sites in postybirb have no public facing API, and that doesn't seem to stop things, so that shouldn't be a problem

**Comment by tecknojock** [comment]
Artfight also only allows posting 1 month a year sooo ya, it would be hard to dev and test for.
