### ISSUE TITLE
Attempts to validate video post for e621 even when I am not posting there

### ISSUE THREAD

**Issue by maekern** [mvdicarlo/postybirb#11]
I am attempting to post an mp4 video to derpibooru, and tumblr. I cannot do so, because the error list at the bottom of the screen persistently says "e621 does not support file format: video/mp4". This error blocks me from posting. 

I am not attempting to post to e621, nor am I even logged in to that site, so it seems to be a bug that it is even trying to check.

I'm happy to provide screenshots or logs as needed. If it is relevant, the video file is a bit over 6 megs.

**Comment by mvdicarlo** [comment]
This is actually a typo.

I copied some code from e621 into derpibooru since they are so similar.
What it actually means to say is that Derpibooru does not support mp4.
I'm not sure if the website does actually support that format or not to be honest. Just PostyBirb does not support this behavior.
