### ISSUE TITLE
PostyBirb incorrectly claims mp4 uploads are not supported by Newgrounds.

### ISSUE THREAD

**Issue by maekern** [mvdicarlo/postybirb#12]
Just what is says in the title. If I attempt to post an mp4 video to Newgrounds, the bottom of the PostyBirb window contains the error "Newgrounds does not support file format: video/mp4", but this is incorrect, and I can post the same video directly to newgrounds without issue. The video file is a bit over 6 megs

**Comment by mvdicarlo** [comment]
Its not so much that new grounds that doesn't support it. Its that postybirb doesn't currently support sending mp4 to new grounds.

Newgrounds was added in a hurry and only the minimum of sending images is currently supported.
