### ISSUE TITLE
Not loading past "glue" screen.

### ISSUE THREAD

**Issue by tehFoxx0rz** [mvdicarlo/postybirb#13]
I had some posts scheduled and all was going well, but then my computer froze (which happens often, nothing to do with Postybirb), and after restarting and trying to open Postybirb again, all I get is the initial screen with the dragon. I've left it quite a while, and it's not managed to make its way past that.

Even after uninstalling and reinstalling, it won't seem to go past this screen.

And prior to the freeze, I only saw glimpses of this screen.

Using 2.2.17.

**Comment by mvdicarlo** [comment]
Was this issue resolved?
If you are on Windows you can go to %appdata%/postybirb/data and try deleting files inside there.
If that doesn't work let me know.

**Comment by mvdicarlo** [comment]
Also I would prefer if you have issues to email me at michael.v.dicarlo@gmail.com

**Comment by mvdicarlo** [comment]
Alternatively you can follow these steps and it should fix whatever issue is happening at the expense of losing whatever you had set up
1. Uninstall Application
2. Go to %appdata%/postybirb directory and delete it from your system.
3. Install latest.
