### ISSUE TITLE
Cannot upload images to PostyBirb+

### ISSUE THREAD

**Issue by n3onstars** [mvdicarlo/postybirb#133]
consistently receive error "filename.png failed to upload". I'd take a screenshot of it, but it doesn't show up long enough.

**Comment by leoegidio** [comment]
![image](https://user-images.githubusercontent.com/28789140/199836957-6f5051a5-ec2a-41fe-a898-2b8e4c031ded.png)
this started happening with me today

**Comment by mvdicarlo** [comment]
Usually an issue with Avast. If you are still having issue, please contact through the contact form or discord.
