### ISSUE TITLE
[Feature request] Misskey support

### ISSUE THREAD

**Issue by ThatOneCalculator** [mvdicarlo/postybirb#140]
Support for Misskey/Calckey would be great, and since Mastodon is already supported, would compliment it nicely.

Helpful resources:
- https://www.npmjs.com/package/misskey-js
- https://www.npmjs.com/package/misapi
- https://stop.voring.me/api-doc

**Comment by ThatOneCalculator** [comment]
Was this closed due to being implemented or not planned?

**Comment by ThatOneCalculator** [comment]
Seemingly implemented in 45d18cdae04cdb3abd50b1f1c4acf092cc3a8559

**Comment by mvdicarlo** [comment]
v2 is no longer under development.
This repo is now for v2 efforts so legacy tickets were closed.
