### ISSUE TITLE
Feature Request: Cohost Support

### ISSUE THREAD

**Issue by wolfteeth** [mvdicarlo/postybirb#145]
Would be nice to be able to post to a Cohost page with Postybirb. They don't have a public API yet (I guess it is in the works), but apparently there is currently a python library that deals with the private one, and could be used as reference.

See: https://help.antisoftware.club/support/discussions/topics/62000183038

**Comment by NABU5309** [comment]
Just chiming in, this would be really useful with how things are kind of scattered around.
