### ISSUE TITLE
Claims that submission to Weasyl failed despite success

### ISSUE THREAD

**Issue by iconmaster5326** [mvdicarlo/postybirb#18]
I'm using Windows 10 and PostyBirb 2.2.55. It managed to successfully submit a post to both Fur Affinity and Weasyl, but the program claims that the submission to Weasyl failed.

Weasyl is very slow today for me. I wonder if site latency issues are causing premature timeouts of some sort on PostyBirb's side.

**Comment by iconmaster5326** [comment]
Attached is the failure log: [PB_FAILURE_Tue, 10 Dec 2019 23_18_04 GMT.log](https://github.com/mvdicarlo/postybirb/files/3947606/PB_FAILURE_Tue.10.Dec.2019.23_18_04.GMT.log)

**Comment by mvdicarlo** [comment]
Log doesn't give much info as to what might have happened unfortunately. Closing for now.
