### ISSUE TITLE
Migrate nx to 15

### ISSUE THREAD

**Issue by mvdicarlo** [mvdicarlo/postybirb#187]
Ensure that react and electron migrate to 15 successfully and build in exe without white screen.

**Comment by leaftail1880** [comment]
Would like to assign this to me.

**Comment by mvdicarlo** [comment]
pleaase ensure nx-electron also gets updated

**Comment by mvdicarlo** [comment]
@leaftail1880 I had to revert your PR.
When it merged into main it was no longer able to build the ui portion.
I tested your branch before merging into main and it was fine, but something breaks when merging the two.

**Comment by leaftail1880** [comment]
@mvdicarlo looks like main ovverided some package bumps. Ill look into it

**Comment by leaftail1880** [comment]
looked deeper into it. Original problem was related to caniuse lite, strict resolve of this module has helped. However, after running yarn start it does not shows icons. This is related to webpack version and/or plugins that have been changed after migrating and extracting managed webpack config to apps/postybirb-ui/webpack.config.js.

Requires a lot of digging.

**Comment by mvdicarlo** [comment]
https://github.com/mvdicarlo/postybirb/tree/users/mvdicarlo/v16
Created my own branch attempt and just pushed up to v16 and put in vite.
Just need to solve the whole dynamic import problem that exists because eui components use dynamic import svgs for whatever reason.

**Comment by leaftail1880** [comment]
Dynamic icon importing is known issue and there is workarounds for that [here](https://github.com/elastic/eui/issues/5463) 

However, i need to manually mix your solution and mine because we both applied some pathes (for mine thats eslintrc changes and test fixes). I can do that after a week, most likely on 9th october
