### ISSUE TITLE
Issue attaching thumbnails

### ISSUE THREAD

**Issue by scottwolff** [mvdicarlo/postybirb#19]
When I attach a thumbnail, the program goes white in release 2.2.61. See attached screenshot. I went back to the version 2.2.60 and do not have this issue.
![thumbnailpostybirb](https://user-images.githubusercontent.com/19482044/73894576-84b95000-4842-11ea-83d4-bdaed33cf832.png)

**Comment by mvdicarlo** [comment]
This was fixed in .62
