### ISSUE TITLE
Tag Groups Order

### ISSUE THREAD

**Issue by LoboAnimae** [mvdicarlo/postybirb#215]
# Problem 
Tag groups currently appear in the middle of the list of all Tag Groups. When this list increases in size, it is hard to find the new Tag Group. 

# Behavior
### Current Behavior
The tag group gets added to a place in the middle of the list, rather than to the top of the list for easy access. This happens when one or more new tag groups are added.
```
  Existent Tag Group 1
  Existent Tag Group 2
> New Tag Group (Unsaved)
  Existent Tag Group 3
  Existent Tag Group 4
```

### Suggested Behavior
Make it so that the tag group is added to the top of the list, rather than to the middle of it. Make it so that the tag group itself is ordered into the list AFTER it has been saved.
```
> New Tag Group (Unsaved)
  Existent Tag Group 1
  Existent Tag Group 2
  Existent Tag Group 3
  Existent Tag Group 4
```
Becomes after save:
```
  Existent Tag Group 1
  Existent Tag Group 2
  Existent Tag Group 3
> New Tag Group (Saved, ordered now)
  Existent Tag Group 4
```

**Comment by leaftail1880** [comment]
Noted. @mvdicarlo Create ticket for it in todolist?

**Comment by mvdicarlo** [comment]
@LoboAnimae Is this for v4 or v3?
Just checking.

**Comment by LoboAnimae** [comment]
@mvdicarlo I am currently using v3

**Comment by leaftail1880** [comment]
@LoboAnimae this repo is for v4, v3 is https://github.com/mvdicarlo/postybirb-plus

But we mostly work on v4 right now

**Comment by LoboAnimae** [comment]
@leaftail1880 I'll check out v4. If the same thing persists, I'll poke you again. If not, I will close it here too.

Also, be mindful that the downloads in the webpage are for v3 still!

**Comment by leaftail1880** [comment]
v4 is in development, so there is no downloads

**Comment by mvdicarlo** [comment]
Closing since this was a request outside of v4.
