### ISSUE TITLE
Newgrounds posting is broken

### ISSUE THREAD

**Issue by VGBoy** [mvdicarlo/postybirb#218]
Recently, Newgrounds has updated how art posting works on their site, and it causes post attempts in PostyBirb to consistently return as errors. I'm wondering if there's a fix in the works for this.

**Comment by leaftail1880** [comment]
@mvdicarlo and @anneilans are working on it. Note that you created issue on v4 repo, v3 as noted in readme is here: https://github.com/mvdicarlo/postybirb-plus

**Comment by mvdicarlo** [comment]
Image posting should be fixed in latest.
