### ISSUE TITLE
DeviantArt: “Created using AI tools” option

### ISSUE THREAD

**Issue by Gushousekai195** [mvdicarlo/postybirb#226]
Uploading to deviantart through PostyBirb is missing the option to mark uploads as “created using AI tools.” Normally when something is uploaded to DA using PB, the setting defaults to “no,” which leaves any ai-made submissions open to trolling and flaming by anti-ai deviants until each one is manually marked as “yes.” And there’s also a rule on DA requiring ai-made content to be marked as such, and we must comply.

I kindly ask that this option be implemented. It would make things easier for ai users alike.

**Comment by mvdicarlo** [comment]
It is not supported by their API for whatever reason. So it cannot be implemented currently.
