### ISSUE TITLE
Is the lack of a license intentional?

### ISSUE THREAD

**Issue by RonaldZielaznicki** [mvdicarlo/postybirb#244]
The other PostyBirb repos have a BSD 3-Clause license. As stated in their package.json and LICENSE file.

But this repository doesn't look to have ever had a LICENSE file and the MIT license was removed from the package.json in this commit: https://github.com/mvdicarlo/postybirb/commit/f07b512c11b0b77fa2e3c179bb2e5c623409a2ac

Is this intentional?

**Comment by leaftail1880** [comment]
@mvdicarlo

**Comment by mvdicarlo** [comment]
I think it got deleted when I moved over to v4 repo.
Can assume the same license for now as the postybirb-plus repo until otherwise specified.

**Comment by RonaldZielaznicki** [comment]
@leaftail1880 @mvdicarlo 

Thank you both for the help and clarification. Would it be permissible if I were to submit a PR to add the license utilized in `postybirb-plus` here?

**Comment by leaftail1880** [comment]
#245
