### ISSUE TITLE
Implement Data Parsers

### ISSUE THREAD

**Issue by mvdicarlo** [mvdicarlo/postybirb#255]
Can largely take the description parses out of v3 as we will continue to use HTML from TinyMCE.

**Comment by mvdicarlo** [comment]
This should include all data parsing (tag joining and conversion, description parsing, shortcuts)

**Comment by leaftail1880** [comment]
Note that the current solution in v3 has a lot of bugs with newline, espectually when converting html into plaintext or custom format
