### ISSUE TITLE
Winx64 uninstaller detects as treat by WinDefender

### ISSUE THREAD

**Issue by DrKsantor** [mvdicarlo/postybirb#26]
Winx64 uninstaller detected as threat by windows defender. Possible this behavior may be caused by using nsis. As I know it solving by reporting developer to Microsoft about adding WinDefender exception globally.
![photo_2020-03-24_13-21-39](https://user-images.githubusercontent.com/54307321/77415322-5a602980-6dd3-11ea-80a9-71e4f8f015e7.jpg)

**Comment by mvdicarlo** [comment]
This is being dealt with or attempted to be dealt with here https://github.com/electron-userland/electron-builder/issues/4793
