### ISSUE TITLE
bug: i18n breaks UI

### ISSUE THREAD

**Issue by mvdicarlo** [mvdicarlo/postybirb#267]
Cannot work in dev in UI.

![image](https://github.com/mvdicarlo/postybirb/assets/23141042/acd5da35-5f28-4039-8f26-ee1cd09f6102)
![image](https://github.com/mvdicarlo/postybirb/assets/23141042/f85c5975-4fdb-493e-9631-2be8aa75b743)

**Comment by mvdicarlo** [comment]
Try doing it on a fresh clone.
If it works there, I can try recloning again. My env might be acting up. This is the first time I've tried running the UI since the translation code was merged. Been too busy in the posting logic haha.

**Comment by leaftail1880** [comment]
Was able to reproduce it and fix. Seems like i forgot to test latest changes, was busy too, hah. Also fixed those failling actions, but not sure, it can spam commits with empty file changes

**Comment by leaftail1880** [comment]
#269
