### ISSUE TITLE
Failure to post to Picarto after 1st upload

### ISSUE THREAD

**Issue by BlackCatte** [mvdicarlo/postybirb#276]
Picarto is successful to uploading on first submission via Postybirb, but subsequent submissions receive an "unknown error".

**Comment by leaftail1880** [comment]
This is V4 repo, not V3 (PostyBirb+).
Please close this and open new issue on the https://github.com/mvdicarlo/postybirb-plus/ with additional information about error. You can find it by clicking to the Submissions/Logs/View button
