### ISSUE TITLE
DeviantArt flagging posts "created using Ai tools"

### ISSUE THREAD

**Issue by CinnamonGirlIssa** [mvdicarlo/postybirb#285]
I read an old issue that was closed because DeviantArt didn't have the option available because of the API.

I think DeviantArt recently updated the way posts are submitted.  Is it now possible to do this? 

If not, I deeply apologize for opening another issue.  

And I understand if this particular option simply cannot be bypassed.  Are there any recommended alternatives to this situation or should I simply manually edit and flag it as "created using AI tools" after the fact?

**Comment by leaftail1880** [comment]
DeviantArt still didn't update the API, so not possible to add without rewriting the entire integration to go through the website forms instead. 

Also do note that this is the v4 repo, any next v3 issues should be submitted to the https://github.com/mvdicarlo/postybirb-plus

**Comment by mvdicarlo** [comment]
This was updated in v3. This is not a feature that will be updated in v2.
