### ISSUE TITLE
Request: Enable posting directly to Pillowfort communities

### ISSUE THREAD

**Issue by heartlessglasses** [mvdicarlo/postybirb#35]
Hello,

Was just made aware of this app and I love it! I mostly use Pillowfort at the moment, which doesn't yet have a queue and drafts feature, so this app will surely help there until that feature arrives. :3 The one thing that's missing, though, is being able to post directly to communities you've joined. Not reblogging, though if possible that would also be a neat feature as on Pillowfort folks often post to their blogs then reblog to a community, or vice-versa. But mainly, I need to schedule posts directly to a community I mod, and I can only do so to my blog right now.

Hopefully this is possible to implement! I'm really glad for the site override options including Pillowfort's privacy controls and everything, it's quite a nice touch. Thank you! :)

**Comment by mvdicarlo** [comment]
Generally the app isn't to be used for community boards like that. I guess I could see if it is something easy to do? But if it starts having weird stuff needed to be done by the user then I'd probably say no. Also I have no clue how any of the features work on PF so I'd have to figure out how community posts even work in the first place.
