### ISSUE TITLE
Request: Support for Reddit

### ISSUE THREAD

**Issue by feilen** [mvdicarlo/postybirb#37]
I currently use [RedditLater](https://redditlater.com) for submitting art to various parts of Reddit at regular intervals. It would be really nice if postybirb could support the [reddit API](https://www.reddit.com/dev/api/). I could take a crack at it later if nobody's interested, but my JS skills are a bit rusty.

**Comment by mvdicarlo** [comment]
I'd love to implement Reddit support, but the last time that I dug around in the Reddit API I didn't see any way to post images to a subreddit.

Do you know if that is possible?

**Comment by feilen** [comment]
Uh, to my knowledge it requires uploading it to a seperate site. I think reddit has its own image hosting now but it appears as though it's restricted to the official clients only. An alternative would be to upload to imgur, which was the classic solution for reddit before reddit added their own hosting, [but needs to take care to not post them publicly or they'll be removed](https://www.reddit.com/r/help/comments/3732z6/uploading_nsfw_image_to_imgur_imgur_says_i_cant/).

**Comment by feilen** [comment]
Imgur has a fairly well documented API it looks like, and anonymous uploads should be possible as long as the client_id and client_secret exist: https://apidocs.imgur.com/?version=latest

**Comment by feilen** [comment]
An alternative (though I don't know how easy it'd be to implement with the current implementation) would be to require a post to at least one other account, and then post a link to that (or to the image directly). At least on /r/furry and related communities, there's bots that'll mirror content in the comments, but a direct image link will probably be more likely to work with previews in various clients.
