### ISSUE TITLE
Support iwara.tv?

### ISSUE THREAD

**Issue by NintendoManiac64** [mvdicarlo/postybirb#41]
iwara.tv seems to be quite the happening place for 3D artists, particularly for east asian-style 3D works, so is there any chance of adding support for iwara.tv?

**Comment by mvdicarlo** [comment]
I can look into it, although website additions can be pretty slow to occur.

**Comment by mvdicarlo** [comment]
Added to a list of requests in other site. Closing here.

**Comment by NintendoManiac64** [comment]
> Added to a list of requests in other site

Is this list publicly available so I can make sure I'm not re-asking something that may already be on the list?

(I'm also guessing that, since it's been 4 years and Iwara still isn't supported, that progress either stalled or it was determined to not be possible)

**Comment by leaftail1880** [comment]
This program is not stale, its just that sites are mostly being added by contributors now, because lemony is busy with migrating old sites from v3 to v4 and fixing bugs

**Comment by leaftail1880** [comment]
there is no really a big challenge, its just that nobody is willing to implement it right now
