### ISSUE TITLE
Creating a submission from clipboard results in the uploaded file being a JPG instead of a PNG like expected

### ISSUE THREAD

**Issue by TisFoolish** [mvdicarlo/postybirb#59]
PostyBirb version: 2.3.23
Platform: Win 10 x64
Website: FA with "Reupload better image quality" enabled (that should probably be "Reupload for better image quality")

Steps to repeat:
Copy image from image editor, go to create a new submission in Postybirb using the option "From Clipboard", fill in info, post image, go to submission and see that the upload is a JPG instead of a PNG. Anywhere else where I can upload from clipboard (Discord, Reddit, Imgur) all create PNGs instead of JPGs.

I have an example upload, although I have already fixed the submission by manually reuploading a saved PNG.  However, you can see from the file name that the original file name was "unknown jpeg".  

As a warning the submission is very NSFW. Hyper bits, inflation, spanking, etc.  [Link](https://www.furaffinity.net/view/39561741/)

**Comment by mvdicarlo** [comment]
Limitation of the framework.
