### ISSUE TITLE
Can't enter ampersands in tags

### ISSUE THREAD

**Issue by The-Polymorphic** [mvdicarlo/postybirb#69]
I don't like how it's impossible to enter ampersands (&) in the tags field. For me, this means I can't enter tags for franchises such as _Lilo & Stitch_, _Dungeons & Dragons_, etc. unless a tag alias using "and" exists for a site. While some sites do avoid using ampersands for tags, there are still a number of websites that PostyBirb supports that do allow them, such as Tumblr, Inkbunny, and Furbooru. This applies to both PostyBirb and PostyBirb+.

**Comment by mvdicarlo** [comment]
Done
