### ISSUE TITLE
Mark Mastodon posts as sensitive media based on existence of spoiler text

### ISSUE THREAD

**Issue by jdnielse** [mvdicarlo/postybirb#8]
The current code for marking mastodon images as sensitive is based only on the post rating. It should also be based on the existence of spoiler text. If a post has spoiler text, the text content is already hidden, it's expected that the image will be hidden too (by marking it sensitive).

I tracked it down to here https://github.com/mvdicarlo/postybirb/blob/63d297e1e84b4c6292478c475456ba4abb372a35/src/app/commons/models/website/mastodon.ts#L64 when trying to figure out why my posts weren't being marked sensitive sometimes.

I think if the post is (not general OR spoiler text exists), the image should be marked sensitive.

**Comment by mvdicarlo** [comment]
Is being implemented in the remake.
