### ISSUE TITLE
Login to Mastodon instances broken

### ISSUE THREAD

**Issue by nek0** [mvdicarlo/postybirb#89]
With the newest version of Postybirb (3.0.36) the login function to mastodon seems broken. All I get from the window is:

```
{"errors":[{"statusCode":404,"message":"Cannot GET /mastodon/v2/authorize/https:/mastodon.social","error":"Not Found"}],"statusCode":404,"timestamp":"2021-06-23T02:46:15.532Z","path":"/mastodon/v2/authorize/https:/mastodon.social"}
```

Seems like the path gets assembled the wrong way around.

**Comment by mvdicarlo** [comment]
Sorry for the slow reply. For whatever reason I don't get emails about issues filed here.

I updated the server and seems to be working on my end now after some tweaks (Azure was messing with the url or something).

Give it a go and see if it is fixed for you.

**Comment by nek0** [comment]
Yup. works like a charm. Thanks!
