### ISSUE TITLE
FurAffinity upload changes

### ISSUE THREAD

**Issue by VintageGriffin** [mvdicarlo/postybirb#96]
Hey there.

Thank you for the surprisingly quick fix on FurAffinity's upload changes.
I've browsed through the code to check that everything was okay and noticed a few things that might need some correction or that could be improved a little bit. 
The items below will be referencing line numbers from `/src/app/websites/website-services/fur-affinity/fur-affinity.service.ts`

- `[342:344]`  Flood protection is checked on every step of the upload process. If it didn't trigger on `submit` first, it's not going to trigger on `upload`.
- `[346:348]`  All errors on all pages (with an exception of one, see below) are going to be reported via the page with the `pageid-redirect` ID on the body tag. You can grab the html contents of `<div class="redirect-message">` if you want to display them to the app user.
- `[364:367]`  The `finalize` step now accepts the `cat` request parameter for category regardless of the submission type. It is still a good idea to force a fixed category for non-visual uploads like it's being done right now, as they can't be in any category other than the one for their specific submission type.
- `[392:396]`  CAPTCHA verification is part of the `upload` step now rather than `finalize`.
- `[398:400]`  The `finalize` page will never reload its contents on a POST request. It will either display an error page, redirect back to the `submit` page on an uploaded files missing error (see below), or redirect to a successfully uploaded submission.
- `[402:404]`  This is the only error condition on the `finalize` page that is not displayed via a standard error page. If the temporarily uploaded files from the `upload` step can not for some reason be found on the `finalize` step, the latter will redirect back to `/submit?msg=%d`, which will display the appropriate error message.

**Comment by mvdicarlo** [comment]
@VintageGriffin Thanks for the info, I'll be looking into this. For now what I have is a stopgap.
Have some users getting this error at the moment "Submission Category ID not provided" I assume something is dropping the cat field when I updated it.

**Comment by VintageGriffin** [comment]
@mvdicarlo That's one of the issues I referenced above. The `finalize` step accepts the `cat` attribute for all submission types now, both visual and non-visual. Previously non-visual submissions used the `cat_duplicate` field for specifying category. The current code drops the `cat` field and adds `cat_duplicate` to the request for non-visual submissions, hence the "Submission Category ID not provided" error message. There is no need to do this any more.

**Comment by mvdicarlo** [comment]
@VintageGriffin So this change should be all that is required then?
https://github.com/mvdicarlo/postybirb/commit/2b4c3d38270deab4c2c2e8bff48e48f6fb59f93a

**Comment by VintageGriffin** [comment]
@mvdicarlo That looks about right.

The only minor change I'd advise doing is on lines [395:403]. Instead of detecting whether the URL includes the `?upload-successful` request parameter it would be more reliable to check whether the page has the `id="pageid-submission"` on the `body` tag. All pages on FA have uniquely identifying IDs on their body tags and that is a lot less likely to change than request parameters. The error page has the `id="pageid-redirect"` on it, in case you want to update `processForError()` to match.

It's not a big deal however. Thank you for taking care of this.
