### ISSUE TITLE
ko-fi limits file format; .gif not supported

### ISSUE THREAD

**Issue by pointystick** [mvdicarlo/postybirb#98]
Postybirb's Ko-Fi module doesn't allow the uploading of gifs. (Error: "Currently supported file formats: jpeg, jpg, png") However, gifs appear to upload fine on the ko-fi site itself. Is this an old limitation that needs to be removed, or something behind the scenes?

Perhaps when there's a "format not supported" error, it could instead be a warning and Postybirb will still attempt to upload anyway and thereafter throw an error if it fails rather than completely prevent pressing the post button.

I'm very new to Postybirb, and am making some assumptions on behaviors, but the red alert symbol (/!\) and disabled "Post" button seem easy to understand.

Using 3.0.39

**Comment by mvdicarlo** [comment]
Might be an old limitation. I can check it out.
v3 is actually a different report postybirb-plus.
